### ISSUE TITLE
Patient260 Incomplete Chromosome Coverage

### ISSUE THREAD

**Issue by SRHilz** [HenrikBengtsson/Costello-PSCN-Seq#15] opened 2018-04-19 22:25 UTC
I have run into a peculiar issue with Patient260. Large regions of the genome are absent from the final copy number report + rds output files:

<img width="839" alt="screen shot 2018-04-19 at 3 08 26 pm" src="https://user-images.githubusercontent.com/5839184/39021068-1f0711fc-43e4-11e8-9418-808b762f30b9.png">

When inspecting the individual bins in the $data structure of the final .rds files, many bins are missing from each sample. From the LoH plot for this patient (included below), it does not appear there is an issue with identifying enough heterozygous snps.

Have you ever seen a case like this before?

Many thanks for any help you can give! I have attached a few of the .pdf final files as examples, as well as coverage and quality plots - while the normal has better coverage than most of the tumor samples, it isn't that much higher. The rds files are in /costellolab/shilz/data/cotient260tmp/

![patient260 loh](https://user-images.githubusercontent.com/5839184/39021275-ea50d834-43e4-11e8-8fd1-4a600577a2a4.png)
[Patient260,Z00520_vs_Z00249,PairedPSCBS,report.pdf](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1929931/Patient260.Z00520_vs_Z00249.PairedPSCBS.report.pdf)
[Patient260,Z00519_vs_Z00249,PairedPSCBS,report.pdf](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1929932/Patient260.Z00519_vs_Z00249.PairedPSCBS.report.pdf)
[Patient260,Z00314_vs_Z00249,PairedPSCBS,report.pdf](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1929933/Patient260.Z00314_vs_Z00249.PairedPSCBS.report.pdf)
[overall_basequality.pdf](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1929934/overall_basequality.pdf)
[coverage.pdf](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1929935/coverage.pdf)
[samples.txt](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1929937/samples.txt)

**Comment by HenrikBengtsson** [comment] 2018-04-27 18:50
Yes, the mpileup step is "atomic" in the sense that it tells `samtools mpileup` to write to a *.tmp file and it will only drop the *.tmp extension if the `samtools` step had exit code 0 (= success; completed) (\*).  After this step it gzip's the file - the [gzip step is also "atomic"](https://github.com/HenrikBengtsson/R.utils/blob/master/R/compressFile.R#L158-L192).  Because of this, my best guess is that those reads fail in the  `samtools mpileup` or before.

Q. If you use option `-v` to `ls`, you can sort your file in a human-friendly order (here, by chromosome), e.g. `ls -lv`. If you do that, do file sizes correlate with chromosome size?  Or is the output getting corrupted randomly?

Q. The [`1.mileup.R`](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/blob/master/1.mpileup.R#L99) script outputs the R `sessionInfo()`.  What does that say?  I doubt that will give any obvious clues, but always useful to document that here.  Also, in all that "verbose" output, can you spot what version of Samtools you're running.

One approach of ruling out we're not getting weird behavior due to some of the external R packages or software like Samtools is to rerun one of the old samples and see if those results still make sense.


(\*) The code is (https://github.com/HenrikBengtsson/aroma.seq/blob/master/R/mpileup.R#L236-L240):
```r
        pathnameT <- pushTemporaryFile(pathnameD)
	ans <- samtoolsMpileup(refFile=getPathname(fa), bamFile=getPathname(bam), pathnameD=pathnameT, r=chr, Q=Q, verbose=verbose)
	if (ans == 0L) popTemporaryFile(pathnameT)
        mp <- MPileupFile(pathnameD)
	gzip(mp)
```

**Comment by SRHilz** [comment] 2018-05-11 22:31
Thanks for all of the helpful troubleshooting questions. After pursuing them through many troubleshooting runs, I determined that it is not just Patient260, but all patients run through the copy number pipeline after Nov 27, 2017 that are affected (so Patient340 and 260, plus an even new patient I ran as a test, Patient452).  This is regardless of when the patient exome data was generated, so it seems definitive that it is a copy number pipeline/run issue and not sample issue.

I then checked the sessionInfo() for those prior to Nov 27 to those after it. In summary, the only differences in versions between working and non-working runs were for R and a few of the loaded, non-attached packages (shown in snapshot below). There were no differences in versions of aroma.seq, aroma.core, or Rsamtools. Do you see any one tool in the snapshot below of changed versions that stands out as one that might be causing this issue?

<img width="327" alt="screen shot 2018-05-11 at 3 26 03 pm" src="https://user-images.githubusercontent.com/5839184/39949565-582ccf96-5530-11e8-870b-b4579a798144.png">



Here is all sessionInfo() output relevant to package versions if helpful:

**_sessionInfo() Prior to Nov 27 (when the pipeline was working):_**

= sessionInfo() ===============================================================
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)

Matrix products: default
BLAS: /home/shared/cbc/software_cbc/R/R-3.4.2-20170928/lib64/R/lib/libRblas.so
LAPACK: /home/shared/cbc/software_cbc/R/R-3.4.2-20170928/lib64/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] aroma.seq_0.9.2         future.batchtools_0.5.0 future_1.5.0           
[4] aroma.core_3.1.0        R.devices_2.15.1        R.filesets_2.11.0      
[7] R.utils_2.5.0           R.oo_1.21.0             R.methodsS3_1.7.1      

loaded via a namespace (and not attached):
 [1] RColorBrewer_1.1-2         compiler_3.4.2            
 [3] GenomeInfoDb_1.12.2        XVector_0.16.0            
 [5] zlibbioc_1.22.0            methods_3.4.2             
 [7] prettyunits_1.0.2          base64enc_0.1-4           
 [9] bitops_1.0-6               tools_3.4.2               
[11] progress_1.1.2             digest_0.6.12             
[13] lattice_0.20-35            checkmate_1.8.2           
[15] R.cache_0.12.0             Matrix_1.2-11             
[17] DelayedArray_0.2.7         parallel_3.4.2            
[19] R.rsp_0.41.0               GenomeInfoDbData_0.99.0   
[21] hwriter_1.3.2              gtools_3.5.0              
[23] Biostrings_2.44.1          S4Vectors_0.14.3          
[25] PSCBS_0.62.0               globals_0.10.0            
[27] rappdirs_0.3.1             IRanges_2.10.2            
[29] grid_3.4.2                 stats4_3.4.2              
[31] Biobase_2.36.2             data.table_1.10.4         
[33] listenv_0.6.0              R6_2.2.2                  
[35] DNAcopy_1.50.1             BiocParallel_1.10.1       
[37] base64url_1.2              latticeExtra_0.6-28       
[39] magrittr_1.5               GenomicAlignments_1.12.1  
[41] Rsamtools_1.28.0           GenomicRanges_1.28.3      
[43] backports_1.1.0            batchtools_0.9.3          
[45] codetools_0.2-15           matrixStats_0.52.2        
[47] BiocGenerics_0.22.0        SummarizedExperiment_1.6.3
[49] ShortRead_1.34.0           assertthat_0.2.0          
[51] brew_1.0-6                 stringi_1.1.5             
[53] RCurl_1.95-4.8            

**_sessionInfo() After Nov 27 (when the pipeline was not working correctly):_**

= sessionInfo() ===============================================================
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)

Matrix products: default
BLAS: /home/shared/cbc/software_cbc/R/R-3.4.3-20171130/lib64/R/lib/libRblas.so
LAPACK: /home/shared/cbc/software_cbc/R/R-3.4.3-20171130/lib64/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] aroma.seq_0.9.2         future.batchtools_0.5.0 future_1.5.0           
[4] aroma.core_3.1.0        R.devices_2.15.1        R.filesets_2.11.0      
[7] R.utils_2.5.0           R.oo_1.21.0             R.methodsS3_1.7.1      

loaded via a namespace (and not attached):
 [1] RColorBrewer_1.1-2         compiler_3.4.3            
 [3] GenomeInfoDb_1.12.2        XVector_0.16.0            
 [5] zlibbioc_1.22.0            methods_3.4.3             
 [7] prettyunits_1.0.2          base64enc_0.1-4           
 [9] bitops_1.0-6               tools_3.4.3               
[11] progress_1.1.2             digest_0.6.12             
[13] lattice_0.20-35            checkmate_1.8.2           
[15] R.cache_0.12.0             Matrix_1.2-12             
[17] DelayedArray_0.2.7         parallel_3.4.3            
[19] R.rsp_0.41.0               GenomeInfoDbData_0.99.0   
[21] hwriter_1.3.2              gtools_3.5.0              
[23] Biostrings_2.44.1          S4Vectors_0.14.3          
[25] PSCBS_0.62.0               globals_0.10.0            
[27] rappdirs_0.3.1             IRanges_2.10.2            
[29] grid_3.4.3                 stats4_3.4.3              
[31] Biobase_2.36.2             data.table_1.10.4         
[33] listenv_0.6.0              R6_2.2.2                  
[35] DNAcopy_1.50.1             BiocParallel_1.10.1       
[37] base64url_1.2              latticeExtra_0.6-28       
[39] magrittr_1.5               GenomicAlignments_1.12.1  
[41] Rsamtools_1.28.0           GenomicRanges_1.28.3      
[43] backports_1.1.0            batchtools_0.9.3          
[45] codetools_0.2-15           matrixStats_0.52.2        
[47] BiocGenerics_0.22.0        SummarizedExperiment_1.6.3
[49] ShortRead_1.34.0           assertthat_0.2.0          
[51] brew_1.0-6                 stringi_1.1.5             
[53] RCurl_1.95-4.8

**Comment by HenrikBengtsson** [comment] 2018-05-12 02:58
Wow, that's an interesting observation. I'll investigate asap. There shouldn't be anything dramatic changed between those package versions, which just reflect the difference between R 3.4.3 and R 3.4.2 (basically just but fixes) and a small update in the Matrix package. Except for Matrix, you control the versions, by freezing to module load r/3.4.2. To freeze other R package versions (here Matrix) we need to setup a specific R library. I'll show how to do that later.

What could also make a difference are version updates in external HTSeq tools (which can be controlled via modules). I think this is more likely given your R package diffs.  I'll try to make a list of exactly which tools are used in the pipeline.

**Comment by HenrikBengtsson** [comment] 2018-05-12 08:58
One more clarification:  Regardless of whether you use R 3.4.0, 3.4.1, 3.4.2, 3.4.3, ..., 3.4.z, you will use the exact same package library (= set of packages) you've installed, because it is only the major and minor version (here 3.4) that counts - all use the same package library path:
```r
> .libPaths()[1]
[1] "/home/hb/R/x86_64-pc-linux-gnu-library/3.4"
```
This is true for all package you install as a user.  The packages that come with the R installation itself have the same version as R (here 'methods', 'stats4', and 'tools').   The 'Matrix' package is also "in there" because it is a special package.

**Comment by HenrikBengtsson** [comment] 2018-05-12 09:38
# Samtools

It could be that updates to the samtools software could be the cause:

```
modules         date
samtools/1.3.1  2016-04-22
samtools/1.6    2017-12-04
samtools/1.7    2018-03-05
```

I've looked at [the changlog](https://github.com/samtools/samtools/releases) and the following change in samtools 1.4.0 caught my attention:

* Added -a option to samtools mpileup to show all locations, including
  sites with zero depth; repeating the option as -aa or -a -a additionally
  shows reference sequences without any reads mapped to them (#496).

* The mpileup text output no longer contains empty columns at zero coverage
  positions.  Previously it would output "...0\t\t..." in some circumstances
  (zero coverage due to being below a minumum base quality); this has been
  fixed to output as "...0\t*\t*..." with placeholder '*' characters as in
  other zero coverage circumstances (see PR #537).

**Comment by HenrikBengtsson** [comment] 2018-05-12 09:55
I've pushed updated to `master` branch with PBS scripts that will freeze the R version and the samtools version.  Launch all steps as:
```sh
$ qsub -d $(pwd) 1-4.submit_all.pbs
```
See also the updated [README](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/blob/master/README.md).

I hope that freezing to samtools 1.3.1 solves this.

**Comment by SRHilz** [comment] 2018-05-14 00:15
Thanks, these scripts help a lot in allowing more control over which versions of tools are being used! I just finished rerunning them on my test Patient, Patient147, both with R 3.4.3 and 3.4.2 (and samtools 1.3.1). However, it is still producing the same error as before regardless of the R version. Here is the final report summary plot for Patient147,Z00220_vs_Z00334

<img width="884" alt="screen shot 2018-05-13 at 1 30 41 pm" src="https://user-images.githubusercontent.com/5839184/39971560-1bfd3ae6-56b2-11e8-8cca-56e4748a5125.png">

Could the problem be occurring at the sequenza phase? The mpileup files for a given sample sort nicely in a logical chromosome size order by file size, but I do not see this at the .seqz file phase:

<img width="617" alt="screen shot 2018-05-13 at 1 35 10 pm" src="https://user-images.githubusercontent.com/5839184/39971725-051ae74e-56b5-11e8-857b-249024f6bcc1.png">

Is there a way to force the loading of the version of sequenza that we had been running in Nov 2017 of last year, if it might be different?

**Comment by HenrikBengtsson** [comment] 2018-05-14 03:50
Hmm, this is really odd. Where it's your working directory located? I'd like to peek into your log files to see if there are any clues in there.

About clues in the file sizes: what are the sizes for the germline mpileup files?

I thought about the version of sequenza, which wasn't in your session info output, but the thing is that it hasn't been updated since Oct 2015 (https://cran.r-project.org/web/packages/sequenza/). It's possible to freeze all R package versions by identifying exactly which they were at the time and then reinstall the in a separate location that we point R too. That could help rule out that part.

Do you have original mpileup + seqz files around for a successful run off the past that we can rerun and compare too?

**Comment by SRHilz** [comment] 2018-05-14 16:04
Sure, my relevant working directories are:

1. /costellolab/shilz/tools/Costello-PSCN-Seq_JulBuild - this used to be my only directory for Costello-PSCN-Seq, and contains in it now many subfolders where I have copied the output directories + files [seqData, pscbsData, and reports + logs] for the many troubleshooting runs I have done recently. Most recently, I pulled your updated scripts to it.

2.  /costellolab/shilz/tools/Costello-PSCN-Seq - this is a fresh clone I just made from your github yesterday, so that I could rule out there being any issues with the older clone I had been using; as you will see, it is still, like the original, not working (seqz files are being zipped before completion), and I cannot even get it to produce final .rds files or reports. I have had to restart the run 5 times, but it won't move from .xdr files to .rds files at the pscbs stage.

I unfortunately do not have any original mpileup + seqz files, as there was never a need to keep them, and we have had some space issues in /costellolab.

**Comment by HenrikBengtsson** [comment] 2018-05-25 03:02
Quick update: I suspect it has to do with samtools has been updated since.  I've running with both samtools 1.3.1 and 1.7 and seeing clear file-size differences.  I'll report back when I've finished both tracks.

**Comment by HenrikBengtsson** [comment] 2018-05-25 04:05
Yup, samtools 1.7 (default):

![samtools_1 7](https://user-images.githubusercontent.com/1616850/40525644-23150812-5f96-11e8-9cc6-7638462ed7e5.png)

and with samtools 1.3.1:

![samtools_1 3 1](https://user-images.githubusercontent.com/1616850/40525647-2a3f6268-5f96-11e8-9788-3976907dd481.png)

**Comment by HenrikBengtsson** [comment] 2018-05-25 04:37
I've pushed a fix to the `master` branch.  I've made some minor tweaks to the different *.R and *.pbs that you might wanna use, but those tweaks are irrelevant to the bug itself.  To fix the bug, do:

* copy https://github.com/HenrikBengtsson/Costello-PSCN-Seq/blob/master/.future-configs/batchtools/batchtools.torque.tmpl to the working directory where you launch `1.mpileup.R`.  Note, it is `batchtools.torque.tmpl` (without a period in front).

**Comment by HenrikBengtsson** [comment] 2018-05-28 19:05
> I think this has stressed how even more important it is to make sure all versions are hardcoded in the pipeline - is there anything else that isn't yet hardcoded in but should be? Or some config file with all of the versions to be loaded specified that I could make?

Yes, ... and no.

There are many issues that come with freezing your pipeline.  For example, exactly what should you freeze?  This pipeline depends on R, R packages, and their dependencies, samtools, Python, many system libraries ("libNNN":s) etc.  It also depends on the operating system you run, the hardware and so on.  If you choose to freeze the version this way when you are force updates upon you, e.g. the operating system is updated, you or your collaborators need to run your analysis on another system?  Also, imagine if the authors of samtools say they've discovered a critical bug that affects everyone?  Should you still stick with your old pipeline, or should you update?  Also, when you update one piece, you often have to update several dependencies at the same time.  My point is that it is not as simple as freezing versions and you're done.  If you do, you slowly growing your "technical debt" and your overall uncertainty, and you might get to the point where updating becomes too overwhelming.  You'll also get into situations when you cannot ask maintainers for help because you're running a very old version ("please try with the latest version").  If you freeze versions, I'd say you still need a plan for how to update once in a while.

However we do it, I think writing tests, tests, and more tests is what in the end will help us sleep at night.  In this case, we lacked *redundancy tests*, that is, tests that make sure that we get the same results over time.  The redundancy tests we have are the ones you run and where you inspect the results manually.  But ideally, we want to automate these.  I have quite few unit and redundancy tests for the various R packages and components I wrote, but I don't have anything automated for the pipeline from start to finish.

(We touched upon the above in the discussion around updating the "LG3" pipeline)

Having said all this, I tried to specify the software and their versions everywhere.  This is done in all the `*.pbs` files and the `*.tmpl` file.

> Also, so that I can learn a bit more about the troubleshooting process - I thought for some reason you had fixed the samtools version two weeks ago (see comment above from 14 days ago) and it still wasn't working - was there something else you had to do between then and now to further fix it? It is helpful for me to know so I can make sure I know how to properly fix things. Thanks!

What happened is that the *jobs* that were running `samtools mpileup` internally were not seeing the `module load samtools/1.3.1` change - they don't "inherit" the setup of their parent jobs.  When a job runs, it runs in a clean setup on the cluster with the setup you specify in your `~/.bashrc` file.  If you had set `module load samtools/1.3.1` there, you'd be running samtools 1.3.1.

I made a thinko when I 2+ weeks ago claimed that the new `*.pbs` would fix this.  I did specify `samtools/1.3.1` there and that would have worked if we wouldn't have parallelized across chromosomes.  When we parallelize across chromosomes, each chromosome is processed in a seperate, fresh job on the scheduler.  The solution was to make sure each of those jobs were also specifying `samtools/1.3.1`.  This done in the `*.tmpl` which is the template for the "*.pbs" of ech job.

This was not obvious.  What was worse is that the verbose output does not report on the samtools version used, so it wasn't easy to verify.  At a minimum one should be able figure out what software versions a specify result was produced with so that one can at least troubleshoot.  It's not possible to get versions of everything, but one should leave a trail of "breadcrumbs" such that one can backtrack what the main software tools and their versions were used.  Ideally the log files should provide all these details (but they didn't in this case).  I've [added this to the todo list](https://github.com/HenrikBengtsson/aroma.seq/issues/42#issuecomment-392584182).

**Closed** 2018-07-06 05:31 UTC
